In [1]:
#%pip install graphtsetlinmachine pycuda pandas numpy keras tensorflow scikit-learn scipy tqdm pillow opencv-python optuna
#%pip install git+https://github.com/cair/tmu.git


# !pip uninstall numpy
# !pip install numpy==2.0.0

In [2]:
import os
from pathlib import Path
from GraphTsetlinMachine.tm import MultiClassGraphTsetlinMachine
from sklearn.metrics import classification_report, confusion_matrix
from src.datahandler import DataHandler
from src.graphhandler import GraphHandler

#from tqdm.auto import tqdm 

In [3]:
os.makedirs("data", exist_ok=True)
os.makedirs("models", exist_ok=True)
os.makedirs("graphs", exist_ok=True)

In [4]:
paths = {
    "data": Path("data"),
    "models": Path("models"),
    "graphs": Path("graphs"),
}

In [5]:
hypervector_bits = 2
hypervector_size = 64
board_size = 3
n_samples = 10000

dataset = f"{board_size}x{board_size}"

In [6]:
dh = DataHandler(paths=paths, files={'data': '3x3'}, dataloader='np.genfromtxt', n_samples=n_samples)

In [7]:
print(dh.n_samples)
print(dh)
print(dh.X_train.shape)
print(dh.y_train.shape)
print(dh.X_test.shape)
print(dh.y_test.shape)
print(dh.get_class_distribution())
print(f"Data balanced? {dh.is_data_balanced}")
dh.show_data_info()

10000
(8000, 9)
(8000,)
(2000, 9)
(2000,)
[5000 5000]
Data balanced? True
Data shape: (20000, 10)
X shape: (10000, 9)
y shape: (10000,)
Headers: ['cell0_0', 'cell0_1', 'cell0_2', 'cell1_0', 'cell1_1', 'cell1_2', 'cell2_0', 'cell2_1', 'cell2_2', 'winner']
X_train shape: (8000, 9)
y_train shape: (8000,)
X_test shape: (2000, 9)
y_test shape: (2000,)


In [8]:
g_train = GraphHandler(paths=paths,
                        files={'data': '3x3'},
                        board_size=board_size,
                        data_array=dh.X_train,
                        symbols=['RED', 'BLUE','UP', 'DOWN', 'RIGHT','LEFT'],
                        hypervector_size=hypervector_size,
                        hypervector_bits=hypervector_bits,
                        verbose_level=2)

g_train.build_complete_graphs()

Setting number of nodes to 13
Adding nodes
Adding edges and properties
Encoding graphs


In [9]:
print(g_train.n_nodes)
print(g_train.symbols)
print(g_train.max_index)
print(g_train.right_index)
print(g_train.left_index)
print(g_train.down_index)
print(g_train.up_index)
g_train.graphs.print_graph(0)

9
['RED', 'BLUE', 'UP', 'DOWN', 'RIGHT', 'LEFT', 'ROW_0', 'COL_0', 'ROW_1', 'COL_1', 'ROW_2', 'COL_2']
8
9
10
11
12
RED * * * * * ROW_0 COL_0 * * * * * BLUE * * * * ROW_0 * * COL_1 * * RED * * * * * ROW_0 * * * * COL_2 * BLUE * * * * * COL_0 ROW_1 * * * * BLUE * * * * * * ROW_1 COL_1 * * * BLUE * * * * * * ROW_1 * * COL_2 RED * * * * * * COL_0 * * ROW_2 * RED * * * * * * * * COL_1 ROW_2 * * * * * * * * * * * ROW_2 COL_2 * * * * RIGHT * * * * * * * * * * * * LEFT * * * * * * * * * DOWN * * * * * * * * * * UP * * * * * * * * * 


In [10]:
g_test = GraphHandler(data_array=dh.X_test, init_with=g_train.graphs, verbose_level=2)
g_test.build_complete_graphs()

Setting number of nodes to 13
Adding nodes
Adding edges and properties
Encoding graphs


In [11]:
print(g_test.n_nodes)
print(g_test.symbols)
print(g_test.max_index)
print(g_test.right_index)
print(g_test.left_index)
print(g_test.down_index)
print(g_test.up_index)
g_test.graphs.print_graph(0)

9
['RED', 'BLUE', 'UP', 'DOWN', 'RIGHT', 'LEFT', 'ROW_0', 'COL_0', 'ROW_1', 'COL_1', 'ROW_2', 'COL_2']
8
9
10
11
12
RED * * * * * ROW_0 COL_0 * * * * RED * * * * * ROW_0 * * COL_1 * * * BLUE * * * * ROW_0 * * * * COL_2 * * * * * * * COL_0 ROW_1 * * * RED * * * * * * * ROW_1 COL_1 * * * BLUE * * * * * * ROW_1 * * COL_2 * BLUE * * * * * COL_0 * * ROW_2 * * BLUE * * * * * * * COL_1 ROW_2 * RED * * * * * * * * * ROW_2 COL_2 * * * * RIGHT * * * * * * * * * * * * LEFT * * * * * * * * * DOWN * * * * * * * * * * UP * * * * * * * * * 


In [12]:
# Save and load graphs in order to verify that they will work in other scripts/notebooks
dh.save_graphs(g_train.graphs, g_test.graphs)
graphs_train, graphs_test, X_train, y_train, X_test, y_test = dh.load_graphs()

In [13]:
# Verify sizes and shapes
print(f"Number of Graphs: {graphs_train.number_of_graphs}")
print(f"Number of Nodes: {graphs_train.number_of_nodes}")
print(f"X Shape: {graphs_train.X.shape}")
print(f"Edge Array Shape: {graphs_train.edge.shape}")

# Check indices
print(f"Node Index Array: {graphs_train.node_index}")
print(f"Edge Index Array: {graphs_train.edge_index}")


Number of Graphs: 8000
Number of Nodes: 104000
X Shape: (104000, 4)
Edge Array Shape: (480000, 2)
Node Index Array: [     0     13     26 ... 103961 103974 103987]
Edge Index Array: [     0      5     10 ... 479991 479994 479997]


In [14]:
number_of_nodes = board_size*board_size
number_of_clauses = 300
T = number_of_clauses*0.875
depth = 3#7
s = 2.0
message_size = 32
message_bits = 2
max_included_literals = 32
number_of_states = 200
epochs = 15

In [15]:
tm = MultiClassGraphTsetlinMachine(
    number_of_clauses,
    T,
    s,
    depth=depth, 
    message_size = message_size,
    message_bits = message_bits,
    number_of_state_bits = 8,
    boost_true_positive_feedback = 1,
    grid=(16*13,1,1),
    block=(128,1,1)
)

Initialization of sparse structure.


In [16]:
for i in range(epochs):
    tm.fit(graphs_train, y_train, epochs=1, incremental=True)
  
    result_test = 100 * (tm.predict(graphs_test) == y_test).mean()
    result_train = 100 * (tm.predict(graphs_train) == y_train).mean()
    
    print("#%d Testing Accuracy: %.2f%% Training Accuracy: %.2f%%" % (i+1, result_test, result_train))
  

#1 Testing Accuracy: 76.00% Training Accuracy: 75.71%
#2 Testing Accuracy: 83.25% Training Accuracy: 83.89%
#3 Testing Accuracy: 83.80% Training Accuracy: 83.59%
#4 Testing Accuracy: 90.20% Training Accuracy: 91.51%
#5 Testing Accuracy: 86.20% Training Accuracy: 87.22%
#6 Testing Accuracy: 90.20% Training Accuracy: 89.70%
#7 Testing Accuracy: 88.50% Training Accuracy: 88.20%
#8 Testing Accuracy: 87.75% Training Accuracy: 88.04%
#9 Testing Accuracy: 92.60% Training Accuracy: 92.96%
#10 Testing Accuracy: 89.45% Training Accuracy: 89.80%
#11 Testing Accuracy: 88.45% Training Accuracy: 88.39%
#12 Testing Accuracy: 87.30% Training Accuracy: 88.45%
#13 Testing Accuracy: 91.25% Training Accuracy: 91.06%
#14 Testing Accuracy: 83.55% Training Accuracy: 84.38%
#15 Testing Accuracy: 81.20% Training Accuracy: 82.16%


In [17]:
tm.score(graphs_test)

array([[-577,  546],
       [-454,  487],
       [  61, -123],
       ...,
       [-626,  540],
       [-221,  281],
       [-629,  569]], dtype=int32)

In [18]:
predictions = tm.predict(graphs_test)
predictions.mean()

0.615

In [19]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.91      0.69      0.79      1012
           1       0.75      0.93      0.83       988

    accuracy                           0.81      2000
   macro avg       0.83      0.81      0.81      2000
weighted avg       0.83      0.81      0.81      2000



In [20]:
confusion_matrix(y_test, predictions)

array([[703, 309],
       [ 67, 921]])

In [21]:
graphs_train.hypervectors

array([[28, 20],
       [24,  1],
       [62, 52],
       [ 9, 61],
       [ 6, 31],
       [ 3,  1],
       [53, 38],
       [57, 12],
       [ 6, 29],
       [14, 45],
       [55, 54],
       [59,  8]], dtype=uint32)

In [22]:
weights = tm.get_state()[1].reshape(2, -1)
for i in range(tm.number_of_clauses):
        print("Clause #%d W:(%d %d)" % (i, weights[0,i], weights[1,i]), end=' ')
        l = []
        for k in range(hypervector_size * 2):
            if tm.ta_action(0, i, k):
                if k < hypervector_size:
                    l.append("x%d" % (k))
                else:
                    l.append("NOT x%d" % (k - hypervector_size))
        print(" AND ".join(l))

Clause #0 W:(2 54) x6 AND x12 AND x57 AND NOT x0 AND NOT x2 AND NOT x3 AND NOT x4 AND NOT x5 AND NOT x7 AND NOT x8 AND NOT x9 AND NOT x10 AND NOT x11 AND NOT x13 AND NOT x14 AND NOT x15 AND NOT x16 AND NOT x17 AND NOT x18 AND NOT x19 AND NOT x20 AND NOT x21 AND NOT x22 AND NOT x23 AND NOT x25 AND NOT x26 AND NOT x27 AND NOT x28 AND NOT x30 AND NOT x31 AND NOT x32 AND NOT x33 AND NOT x34 AND NOT x35 AND NOT x36 AND NOT x37 AND NOT x38 AND NOT x39 AND NOT x40 AND NOT x41 AND NOT x42 AND NOT x43 AND NOT x44 AND NOT x45 AND NOT x46 AND NOT x47 AND NOT x48 AND NOT x49 AND NOT x50 AND NOT x51 AND NOT x52 AND NOT x53 AND NOT x56 AND NOT x58 AND NOT x59 AND NOT x60 AND NOT x61 AND NOT x62 AND NOT x63
Clause #1 W:(48 -47) x1 AND x8 AND x24 AND x38 AND x53 AND x59 AND NOT x0 AND NOT x2 AND NOT x3 AND NOT x4 AND NOT x5 AND NOT x6 AND NOT x7 AND NOT x9 AND NOT x10 AND NOT x11 AND NOT x12 AND NOT x13 AND NOT x14 AND NOT x15 AND NOT x16 AND NOT x17 AND NOT x18 AND NOT x19 AND NOT x20 AND NOT x21 AND